// This file is generated by generate-gallery-data.js
window.galleryData = {
  "bestMoments": [
    {
      "src": "images/moments/moment1.webp",
      "alt": "Best wedding moment moment 1"
    },
    {
      "src": "images/moments/moment4.webp",
      "alt": "Best wedding moment moment 4"
    },
    {
      "src": "images/moments/moment5.webp",
      "alt": "Best wedding moment moment 5"
    }
  ],
  "ceremony": [
    {
      "src": "images/ceremony/ceremony1.webp",
      "alt": "Wedding ceremony ceremony 1"
    },
    {
      "src": "images/ceremony/ceremony2.webp",
      "alt": "Wedding ceremony ceremony 2"
    },
    {
      "src": "images/ceremony/ceremony3.webp",
      "alt": "Wedding ceremony ceremony 3"
    }
  ],
  "family": [
    {
      "src": "images/family/family1.webp",
      "alt": "Family portrait family 1"
    },
    {
      "src": "images/family/family2.webp",
      "alt": "Family portrait family 2"
    },
    {
      "src": "images/family/family3.webp",
      "alt": "Family portrait family 3"
    },
    {
      "src": "images/family/family4.webp",
      "alt": "Family portrait family 4"
    },
    {
      "src": "images/family/family5.webp",
      "alt": "Family portrait family 5"
    },
    {
      "src": "images/family/family6.webp",
      "alt": "Family portrait family 6"
    },
    {
      "src": "images/family/family7.webp",
      "alt": "Family portrait family 7"
    },
    {
      "src": "images/family/family8.webp",
      "alt": "Family portrait family 8"
    }
  ],
  "reception": [
    {
      "src": "images/reception/reception1.webp",
      "alt": "Wedding reception reception 1"
    },
    {
      "src": "images/reception/reception2.webp",
      "alt": "Wedding reception reception 2"
    }
  ],
  "silentHeroes": [
    {
      "src": "images/heroes/MCN_4892.JPG",
      "alt": "Silent hero MCN 4892"
    },
    {
      "src": "images/heroes/MCN_4893.JPG",
      "alt": "Silent hero MCN 4893"
    },
    {
      "src": "images/heroes/MCN_4894.JPG",
      "alt": "Silent hero MCN 4894"
    },
    {
      "src": "images/heroes/MCN_4895.JPG",
      "alt": "Silent hero MCN 4895"
    },
    {
      "src": "images/heroes/MCN_4896.JPG",
      "alt": "Silent hero MCN 4896"
    },
    {
      "src": "images/heroes/MCN_4907.JPG",
      "alt": "Silent hero MCN 4907"
    }
  ]
};
